NM=int(input("Mes:"))
A=int(input("Año:"))

if A%4==0:
    print("Año bisiesto")
    if NM==1:print("Mes:Enero","\nDias:31")
    elif NM==2:print("Mes:Febrero","\nDias:29")
    elif NM==3:print("Mes:Marzo","\nDias:31")
    elif NM==4:print("Mes:Abril","\nDias:30")
    elif NM==5:print("Mes:Mayo","\nDias:31")
    elif NM==6:print("Mes:Junio","\nDias:30")
    elif NM==7:print("Mes:Julio","\nDias:31")
    elif NM==8:print("Mes:Agosto","\nDias:31")
    elif NM==9:print("Mes:Septiembre","\nDias:30")
    elif NM==10:print("Mes:Octubre","\nDias:30")
    elif NM==11:print("Mes:Noviembre","\nDias:30")
    else:print("Mes:Diciembre","\nDias:31")
else:
    if NM==1:print("Mes:Enero","\nDias:31")
    elif NM==2:print("Mes:Febrero","\nDias:28")
    elif NM==3:print("Mes:Marzo","\nDias:31")
    elif NM==4:print("Mes:Abril","\nDias:30")
    elif NM==5:print("Mes:Mayo","\nDias:31")
    elif NM==6:print("Mes:Junio","\nDias:30")
    elif NM==7:print("Mes:Julio","\nDias:31")
    elif NM==8:print("Mes:Agosto","\nDias:31")
    elif NM==9:print("Mes:Septiembre","\nDias:30")
    elif NM==10:print("Mes:Octubre","\nDias:30")
    elif NM==11:print("Mes:Noviembre","\nDias:30")
    else:print("Mes:Diciembre","\nDias:31")
